---
- hosts: localhost
  vars:
   - vm_name: alpine
   - alpine_file: /mnt/NAS/images/alpine
  tasks:
    - name: Create Alpine Vm and run scripts
      command: /usr/bin/packer build -force update-alpine.json
      args:
        chdir: /mnt/workspace/gitlab/packer-templates/openstack
    - name : Delete old alpine image in openstack
      os_image:
        auth:
          auth_url: http://controller:5000
          username: admin
          password: openstack
          project_name: admin
          domain_name: Default
        name: "{{ vm_name }}"
        state: absent
    - name : Upload alpine image to openstack
      os_image:
        auth:
          auth_url: http://controller:5000
          username: admin
          password: openstack
          project_name: admin
          domain_name: Default
        name: "{{ vm_name }}"
        state: present
        container_format: bare
        disk_format: qcow2
        filename: "{{ alpine_file }}"